-- ============================================================================
-- 0010_add_ticket_number_and_developer.sql
-- Adds a human-friendly sequential ticket number and an optional assigned
-- developer (profile) to tickets, so the board can search/filter by
-- description/title, ticket number, and developer.
-- ============================================================================

alter table tickets
  add column ticket_number integer generated by default as identity,
  add column developer_id uuid references profiles (id) on delete set null;

alter table tickets
  add constraint tickets_ticket_number_key unique (ticket_number);

create index tickets_developer_id_idx on tickets (developer_id);

-- Extend the existing cross-reference integrity trigger so developer_id,
-- like client_id/type_id/sprint_id, must belong to the ticket's own
-- organization. developer_id references profiles (no organization_id of
-- its own), so membership in the org is checked via memberships instead.
create or replace function validate_ticket_references()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_board_org_id uuid;
  v_status_board_id uuid;
begin
  select organization_id into v_board_org_id from boards where id = new.board_id;
  if v_board_org_id is null or v_board_org_id <> new.organization_id then
    raise exception 'board_id does not belong to this ticket''s organization';
  end if;

  select board_id into v_status_board_id from statuses where id = new.status_id;
  if v_status_board_id is null or v_status_board_id <> new.board_id then
    raise exception 'status_id does not belong to this ticket''s board';
  end if;

  if new.sprint_id is not null then
    if not exists (select 1 from sprints where id = new.sprint_id and board_id = new.board_id) then
      raise exception 'sprint_id does not belong to this ticket''s board';
    end if;
  end if;

  if new.client_id is not null then
    if not exists (select 1 from clients where id = new.client_id and organization_id = new.organization_id) then
      raise exception 'client_id does not belong to this ticket''s organization';
    end if;
  end if;

  if new.type_id is not null then
    if not exists (select 1 from ticket_types where id = new.type_id and organization_id = new.organization_id) then
      raise exception 'type_id does not belong to this ticket''s organization';
    end if;
  end if;

  if new.developer_id is not null then
    if not exists (
      select 1 from memberships
      where user_id = new.developer_id and organization_id = new.organization_id
    ) then
      raise exception 'developer_id does not belong to this ticket''s organization';
    end if;
  end if;

  return new;
end;
$$;
